### ISSUE TITLE
Please add LICENSE and Copyright

### ISSUE THREAD

**Issue by allentiak** [grand-stack/grand-stack-starter#1]
Hi,

1) Under which license are you releasing this project?
Apache 2? Or some other one?

2) Who owns the copyright of this code?

Thank you in advance for your reply,
Leandro

**Comment by jexp** [comment]
Yes Apache 2 I add the license, the copyright holder is Neo4j.

**Comment by jexp** [comment]
Done, thanks for the reminder.

**Comment by allentiak** [comment]
You're welcome! Thanks to you, Michael!
