### ISSUE TITLE
/web-angular folder is missing

### ISSUE THREAD

**Issue by lukasmatta** [grand-stack/grand-stack-starter#110]
Hello,
I've tried to use the stack starter by using `npx create-grandstack-app myNewApp` command, however, after installation, there isn't ```/web-angular``` folder. Are there any other commands I should run?

**Comment by johnymontana** [comment]
Hey @lukasmatta - for now the best way to use the Angular frontend version is by using this template repository directly. The create-grandstack-app CLI currently only exposes the `web-react` frontend implementation. We plan to add functionality to the CLI to choose different frontends soon

**Comment by ed42311** [comment]
@lukasmatta hey, working on putting template options together in -> https://github.com/grand-stack/create-grandstack-app/pull/13. let me know if you have any feedback.  

Had to downgrade the angular devkit in https://github.com/grand-stack/grand-stack-starter/issues/113. Let me know if you have any feedback here, not familiar enough with it myself to provide other options.

Thanks for staying on top of this...
Cheers 🐝

**Comment by ed42311** [comment]
Closing this with new release of CLI
