### ISSUE TITLE
yarn create grandstack-app hanging on "Creating scripts configuration"

### ISSUE THREAD

**Issue by spritefullake** [grand-stack/grand-stack-starter#121]
```
 ✖ Creating scripts configuration...
      → EEXIST: file already exists, mkdir '***************/grandStarter/scripts/config'
      Removing unused templates:
       ✔ web-react-ts
       ✔ web-angular
       ✔ mobile_client_flutter
    Initialize git
    Installing Packages with yarn
(node:885) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '***************/grandStarter/scripts/config'

```
Is the error I get. I am using the Neo4j online sandbox but I think there may be an issue with the Creating scripts configuration step.

How to resolve this error? I'm using WSL

Thanks

**Comment by johnymontana** [comment]
Hi @spritefullake I've just pushed an update that should fix this. Could you please try again?

**Comment by ed42311** [comment]
Guess that was an incorrect assumption, going to use this issue to document either manual addition of config or update CLI to check and flag creation of config.

**Comment by johnymontana** [comment]
That brings up a good question - how should the start script handle your non-choice of frontend if you've cloned the repo instead of using create-grandstack-app CLI. I guess the start script should just default to React in the case of missing config.

**Comment by spritefullake** [comment]
@johnymontana Thank you, I tried again and it installed everything (the dependencies did take a while).

**Comment by ed42311** [comment]
> That brings up a good question - how should the start script handle your non-choice of frontend if you've cloned the repo instead of using create-grandstack-app CLI. I guess the start script should just default to React in the case of missing config.

yeh, that's what having this file there manually was meant to address, thought it would be overwritten...

**Comment by ed42311** [comment]
@spritefullake yeh the deps take a minute. wonder if there is a good way to optimize that... ?
