### ISSUE TITLE
Unable to run "yarn seedDb" or "npm run seedDb"

### ISSUE THREAD

**Issue by paulrobhendrickson** [grand-stack/grand-stack-starter#132]
When I try to run "yarn seedDb" or "npm run seedDb" I get the following error

```10:21:54 api:seedDb | Error: Error: There is no procedure with the name `apoc.cypher.doIt` registered for this database instance. Please ensure you've spelled the procedure name correctly and that the procedure is properly deployed.```

Is this something I am doing wrong?

**Comment by xavier-taylor** [comment]
Hi there - I managed to get the grand-stack-starter running today (after some difficulty).

From your error message, the first thing that stands out is `apoc` - have you installed the apoc plugin per the instructions?

Forgive me if that is not a helpful suggestion - hopefully someone else can help in that case.

In the meantime, I might suggest providing some information about your environment. Are you using neo4j desktop or sandbox?

Good luck
