### ISSUE TITLE
Multiple datasources

### ISSUE THREAD

**Issue by g3rd** [grand-stack/grand-stack-starter#30]
First off, thanks for this project! I had taken a few tutorials and mashed them together and had a somewhat working Neo4j backed GraphQL API running. However, this project has closed a lot of missing parts.

Is there any guidance on how to add additional data sources? 

I can't seem to figure out how to have `makeAugmentedSchema` work with other sources.

**Comment by johnymontana** [comment]
Hi @g3rd  - sorry for the delay!

Additional data sources can be added by implementing custom resolvers and passing that resolver map to `makeAugmentedSchema`. There an example in the docs here: https://grandstack.io/docs/graphql-custom-logic#implementing-custom-resolvers
