### ISSUE TITLE
Starter UI query is incorrect.

### ISSUE THREAD

**Issue by dzwarg** [grand-stack/grand-stack-starter#36]
I downloaded and started using the GRANDstack docker-compose.yml file -- thank you for such a quick start!

I ran into a problem in the UI: the initial "usersPaginateQuery" query is written incorrectly. As it is written, it encounters this HTTP 400 error at the API:

Query:

```
query usersPaginateQuery(
  $first: Int
  $offset: Int
  $orderBy: _UserOrdering
) {
  User(first: $first, offset: $offset, orderBy: $orderBy) {
    id
    name
    avgStars
    numReviews
  }
}
```

Response:
```
Variable \"$orderBy\" of type \"_UserOrdering\" used in position expecting type \"[_UserOrdering]\"
```

By adding `[` and `]` around "_UserOrdering" in the query, it then begins working. The correct query is:

```
query usersPaginateQuery(
  $first: Int
  $offset: Int
  $orderBy: [_UserOrdering]
) {
  User(first: $first, offset: $offset, orderBy: $orderBy) {
    id
    name
    avgStars
    numReviews
  }
}
```

**Comment by MattGyverLee** [comment]
Fixed by https://github.com/grand-stack/grand-stack-starter/commit/edccf14ab5d6d3cd0623221badb58017079b32f3
