### ISSUE TITLE
The api is not working

### ISSUE THREAD

**Issue by Nadderley** [grand-stack/grand-stack-starter#47]
I downloaded the latest repo and have been unable to get localhost:4000 to resolve. This should start the GraphQL API in the foreground. Instead, the error is 'Unable to connect'. After reviewing the git page, it appears work was done on ui (last update was 8 days ago). However, the api has not been updated for 2 months.

Under the Docker Compose section of the README the instructions says to make changes to the api/.env. Does that still apply after the latest commit?

**Comment by mobsean** [comment]
I´m not sure if this is a real problem. The api/.env states that API should be under localhost:4001/graphql
and not localhost:4000.

GRAPHQL_LISTEN_PORT=4001
GRAPHQL_URI=http://localhost:4001/graphql

**Comment by Nadderley** [comment]
The api/.env DOES states that API should be under localhost:4001/graphql and not localhost:4000. However, after install the configuration lists the following:

GRAPHQL_LISTEN_PORT=4000
GRAPHQL_URI=http://localhost:4000/graphql
