### ISSUE TITLE
Example using authentication in GRANDstack??

### ISSUE THREAD

**Issue by thelovesmith** [grand-stack/grand-stack-starter#48]
I am trying to set up Authentication in my GrandStack starter. I have scoured the docs and graphql-auth-directives readme but I still can not set up authentication correctly. Is there a FULL working example using authentication in grandstack anywhere?? This would be SOOOO helpful. In the docs there are several different solutions mentioned but I have no idea how to set any of them up correctly. Any example of a fully working using authentication (signup/login) would go a long way.

**Comment by colinskow** [comment]
https://grandstack.io/docs/neo4j-graphql-js-middleware-authorization.html

**Comment by thelovesmith** [comment]
i appreciate you response but I have already scoured the docs and tried their way but couldn't get it working. That is why I asked for a working example. Just something I could use as reference.

**Comment by BrenoMazieiro** [comment]
Take a look at this fork i did.
https://github.com/BrenoMazieiro/grand-stack-starter/blob/master/api/src/interfaces/http/server.js

**Comment by thelovesmith** [comment]
> Take a look at this fork i did.
> https://github.com/BrenoMazieiro/grand-stack-starter/blob/master/api/src/interfaces/http/server.js

Thank you @BrenoMazieiro !!!

**Comment by BrenoMazieiro** [comment]
@thelovesmith  I have updated the fork a bit, with subscriptions and upload file.
packages aswell.
Enjoy! =)

**Comment by thelovesmith** [comment]
I just saw!! Thank so much @BrenoMazieirom Such a great resource!

**Comment by abolishperson** [comment]
> @thelovesmith I have updated the fork a bit, with subscriptions and upload file.
> packages aswell.
> Enjoy! =)

This fork is head-over-shoulders the most important educational-kit for this stack on the web. 

This is the only instance of an complete server-side api flow for authentication AND authorization that I've found that doesn't skip the server-side logic for an auth0 snippet. The exact part that's missing from all the apollo/neo4j-graphql-js/grandstack/ documentation

Thanks so much, after scrapping off a flow this complex (below) the rest of my-first-api-project should be a piece of cake! If there was a comment box where I could insist this fork (or a more developed version of it) surface to the top of the ecosystem documentation list, I'm leaving that comment

![Messages Image(2598102768)](https://user-images.githubusercontent.com/9909517/80447464-716ccc80-88e7-11ea-8251-5a4710e39506.jpeg)
