### ISSUE TITLE
Zeit Now Missing Build Property Error

### ISSUE THREAD

**Issue by dwethe** [grand-stack/grand-stack-starter#50]
When I try to deploy api project, Zeit throws an error about a missing build property.   

Denniss-Mac-mini:api dennis$ now
> Deploying /Applications/grand-stack-starter-master/api under denweth
> Using project api
> Error! Your `package.json` file is missing a `build` property inside the `scripts` property.
More details: https://zeit.co/docs/v2/platform/frequently-asked-questions#missing-build-script
Denniss-Mac-mini:api dennis$ 

Here is what is in the api package.json

{
  "name": "grand-stack-starter-api",
  "version": "0.0.1",
  "description": "API app for GRANDstack",
  "main": "src/index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "./node_modules/.bin/nodemon --exec babel-node src/index.js",
    "seedDb": "./node_modules/.bin/babel-node src/seed/seed-db.js"
  },
  "author": "William Lyon",
  "license": "MIT",
  "dependencies": {
    "apollo-boost": "^0.1.22",
    "apollo-cache-inmemory": "^1.3.11",
    "apollo-client": "^2.4.7",
    "apollo-link-http": "^1.5.7",
    "apollo-server": "^2.2.4",
    "dotenv": "^5.0.1",
    "graphql-tag": "^2.10.0",
    "neo4j-driver": "^1.7.2",
    "neo4j-graphql-js": "^2.1.1",
    "node-fetch": "^2.3.0"
  },
  "devDependencies": {
    "babel-cli": "^6.26.0",
    "babel-preset-env": "^1.7.0",
    "husky": "^1.2.0",
    "lint-staged": "^8.1.0",
    "nodemon": "^1.18.7"
  },
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged"
    }
  },
  "lint-staged": {
    "*.{js,json,css,md,graphql": [
      "prettier --write",
      "git add"
    ]
  }
}

**Comment by MattGyverLee** [comment]
@dwethe , The error message is true...your script called "build" has been deleted, and Zeit requires it.
