### ISSUE TITLE
Newbie question:  Resolver that matches a list of IDs ?

### ISSUE THREAD

**Issue by bwalsh** [grand-stack/grand-stack-starter#54]
Hi,  thanks for a great project.  I was wondering how to provide a list of ids to a resolver.

```
{
  User(["0", "22"]) {_id}
}
```

**Comment by BrenoMazieiro** [comment]
Users(
    id:[Int]
  ): [User]

or 

Users(
    id:[ID]
  ): [User]

And the ql should be something like:

{
  User(id: ["0", "22"]) {_id}
}

Is it?

**Comment by bwalsh** [comment]
@BrenoMazieiro  :  Thanks for the quick response.

That did it.

Schema:
```
  usersById(ids:[ID!]): [User]
    @cypher(
      statement: "MATCH (u:User) WHERE u.id IN $ids RETURN u"
    )
```

Client:
```
{
  usersById(ids: ["u1", "u2"]) {id  name reviews {id}}
}
```
